### ISSUE TITLE
Close SparkContext once data load is done.

### ISSUE THREAD

**Issue by ShahSunny** [goibibo/SqlShift#7]
This is specially necessary when we do something at the end of the code which does not require spark but can take significant time ( even in the worst case ). Current alert on dataplatformops was because we send a mail about the RDS->Redshift jobs at the end of the mail, Because mail server was down. Application kept on doing the continuous retries and occupied the container ( cluster resources ).

**Comment by shivamsharma** [comment]
It is done!!!
